### ISSUE TITLE
Images don't show up

### ISSUE THREAD

**Issue by wisniewski94** [wisniewski94/sprites.js#2]
Script runs before sprite image is loaded, that's why on initialize sprite is invisible.

**Comment by thehamstermuffin** [comment]
Not sure what is this about, it seems fine for me.

**Comment by PrabhuVinod** [comment]
Try reproducing this issue using Throttle(using slower network) in Network tab in Chrome developer tools. Then it is reproducible.

**Comment by wisniewski94** [comment]
@thehamstermuffin +1 to what @PrabhuVinod said. Clearing your cache might help. My bad on not providing enough details. Sorry.
